CREATE TABLE STUDENT(
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(20),
CITY VARCHAR(50),
SALARY INT);
INSERT INTO STUDENT(ID,NAME,CITY,SALARY) VALUES(1,'Amulya','Mysuru',20000);
INSERT INTO STUDENT(ID,NAME,CITY,SALARY) VALUES(2,'Akash','Banglore',25000);
INSERT INTO STUDENT(ID,NAME,CITY,SALARY) VALUES(4,'Shishira','Hyderabad',30000);
INSERT INTO STUDENT(ID,NAME,CITY,SALARY) VALUES(3,'Harmyy','Bangalore',50000);